print "您好，请问有什么可以帮到您的?"
print "1 - 我该穿什么尺码？"
print "2 - 发什么快递？包邮吗？"
print "3 - 退换货须知（重要！！）"
print "bye - 离开聊天"
input $1
switch $1
    case "1"
        print "请问您的性别为？"
        print "1 - 男"
        print "2 - 女"
        input $2
        switch $2
            case "1"
                print "亲，我们暂无男生款短裙"
            case "2"
                print "反转了，原来都是均码"
        retry
    case "2"
        print "不包邮（新疆、西藏等偏远地区除外）"
        retry
    case "3"
        print "不许退不许退不许退！"
        print "886~"
        end
    case "bye"
        print "祝您生活愉快"
    case other
        print "会扣字儿不？"
        retry
print "请对我的服务打分"
input $3
print "本次服务评分为"
print $3
print "再见"
