# 输入$1后输出$1的值
# 若$1值为[1,5]内的整数，输出2*$1，否则输出"other"
# 输入$2,若与$1相同输出"same",否则输出"not same"
input $1
print $1
switch $1
    case "1"
        print "2"
    case "2"
        print "4"
    case "3"
        print "6"
    case other
        switch $1
            case "4"
                print "8"
            case "5"
                print "10"
            case other
                print "other"
input $2
switch $2
    case $1
        print "same"
    case other
        print "not same"
