# 输入$1后输出$1的值
# 若$1值为[1,5]内的整数，输出2*$1，否则输出"other"
# 输入$2,若与$1相同输出"same",否则输出"not same"
input $1
println $1
switch $1
    case "1"
        println "2"
    case "2"
        println "4"
    case "3"
        println "6"
    case other
        switch $1
            case "4"
                println "8"
            case "5"
                println "10"
            case other
                println "other"
input $2
switch $2
    case $1
        println "same"
    case other
        println "not same"
