println "请选择下列选项中正确的一个："
println "a - 北邮学生天天被偷外卖，校领导视而不见，助长歪风邪气"
println "b - 北邮澡堂不消毒导致学生感染跖疣，校医院称其无传染性"
println "c - 北邮在疫情期间严禁学生出入校园，教师家属则毫无限制"
println "d - 北京邮电大学是世界一流大学"
input $2
switch $2
    case "d"
        println "小伙子有觉悟，你滴好处大大滴有"
        print "请输入你的手机号："
        input $1
        print "账号："
        print $1
        println "支付宝到账一元~"
    case other
        println "你有什么目的？是谁指使你发表这些言论？"
        println ""
        retry
